# Root-level secrets
OPENAI_API_KEY="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"

